language: ruby
rvm:
  - 2.0.0
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
  
before_install:
  - cp config/database.travis.yml config/database.yml
before_script:
  - rake db:create db:migrate
