sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - http://publify_hook.ookook.fr/travisci
    on_success: always
    on_failure: never
    on_start: never
